import { Inter } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';
import Providers from '@/app/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Mashoor',
  description: 'Generated by create next app',
  metadataBase: new URL('http://localhost:3000'),
  alternates: {
    canonical: '/',
    languages: {
      en: '/en',
      tr: '/tr',
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning className="light">
      <Providers>
        <body className={`${inter.className} antialiased`}>{children}</body>
      </Providers>
    </html>
  );
}
